### ISSUE TITLE
Cesium 1.0 to-do

### ISSUE THREAD

**Issue by shunter** [AnalyticalGraphicsInc/czml-writer#68]
- [x] Require a `version` property on the document object.
- [x] Remove BC code for pixelOffset
- [x] Remove BC code for Image properties
- [x] Remove extra conjugation in CZML quaternions
- [x] Remove existing vectors/sensors and add AGI extensions which will take their place.

**1.0 push**
- [ ] Add a high-level Document class.
- [ ] Write an explicit test case which will generate a CZML sample/gallery document.
- [ ] Naming inconsistencies between types (rectangular/cartesian vs cartesian2/cartesian3, etc..)
- [ ] Improve generated documentation
- [ ] Review and streamline generated writers API
- [ ] Does JSON schema have a way to define default values?
